name: ✨ Feature Request
description: 建议一个新功能或改进
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你提出功能建议！请详细描述你的想法，这将帮助我们更好地理解和评估你的建议。

  - type: textarea
    id: feature-description
    attributes:
      label: 🚀 功能描述
      description: 清楚简洁地描述你想要的功能
      placeholder: 描述你希望添加的功能...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 💡 动机和背景
      description: 描述为什么需要这个功能，它解决了什么问题？
      placeholder: 解释这个功能的必要性和价值...
    validations:
      required: true

  - type: textarea
    id: detailed-design
    attributes:
      label: 📋 详细设计
      description: 详细描述这个功能应该如何工作
      placeholder: |
        ### 用户界面
        描述预期的界面变更...

        ### API 设计
        描述预期的接口...

        ### 配置选项
        列出需要的新配置选项...
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: 🎯 使用场景
      description: 描述这个功能的典型使用场景
      placeholder: |
        **场景 1:**
        - 用户想要...
        - 系统应该...
        - 预期结果...

        **场景 2:**
        - 用户想要...
        - 系统应该...
        - 预期结果...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 替代方案
      description: 描述你考虑过的替代解决方案或功能
      placeholder: 描述其他可能的实现方式...
    validations:
      required: false

  - type: checkboxes
    id: related-features
    attributes:
      label: 🔗 相关功能
      description: 这个功能与哪些现有功能相关？
      options:
        - label: 私信收发
        - label: 图片上传
        - label: 用户信息获取
        - label: 直播监控
        - label: 扫码登录
        - label: 多开支持
        - label: WebUI 界面
        - label: 配置管理

  - type: dropdown
    id: priority
    attributes:
      label: 📊 优先级
      description: 你认为这个功能的优先级如何？
      options:
        - 🔥 高优先级 (核心功能缺失)
        - 🟡 中优先级 (重要改进)
        - 🟢 低优先级 (锦上添花)
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: 🛠️ 实现复杂度
      description: 你认为实现这个功能的复杂度如何？
      options:
        - 🟢 简单 (配置或小改动)
        - 🟡 中等 (需要一些开发工作)
        - 🔴 复杂 (需要大量开发工作)
        - ❓ 不确定
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: 📸 模拟图/原型
      description: 如果有的话，请拖拽模拟图、线框图或原型到这里
      placeholder: 拖拽图片文件到这里...
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: 📚 参考资料
      description: 提供相关的文档、链接或参考资料
      placeholder: |
        - [相关文档](链接)
        - [参考实现](链接)
        - [相关讨论](链接)
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 💬 额外信息
      description: 在这里添加关于功能请求的任何其他上下文信息
      placeholder: 其他相关信息...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ 检查清单
      description: 请在提交前检查以下项目
      options:
        - label: 我已经搜索了现有的 issues，确认这不是重复的功能请求
          required: true
        - label: 我已经阅读了项目文档和路线图
          required: true
        - label: 这个功能符合项目的目标和范围
          required: true
        - label: 我已经考虑了这个功能对现有用户的影响
          required: false
        - label: 我愿意参与讨论和测试这个功能
          required: false